version: "3"

services:
    platform_api:
        image: node:10-alpine
        container_name: platform_api
        working_dir: /mech4u/platform_api/
        command: yarn start:dev
        env_file:
            - ./.env
        environment:
            NODE_ENV: development
        volumes:
            - ./:/mech4u/platform_api/:consistent
        ports:
            - 8000:8000

    platform_api_db:
        image: postgres:11-alpine
        container_name: platform_api_db
        environment:
            POSTGRES_PASSWORD: 123
            POSTGRES_USER: mech4u
            POSTGRES_DB: mech4u_dev
        volumes:
            - ./platform_api_db/:/var/lib/postgresql/data/:consistent
        ports:
            - 5432:5432

networks:
    default:
        external:
            name: mech4u_network
